import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { ClientProvider } from '@/localization/ClientProvider';
import { Toaster } from '@shadcd/sonner';
import { Dialogs } from '@/widgets/dialogs';
import { Initialization } from '@/widgets/init';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProvider>
          {children}
          <Dialogs />
          <Toaster />
          <Initialization />
        </ClientProvider>
      </body>
    </html>
  );
}
